[package]
name = "rust_client_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "1.3.1"
dotenv = "0.15.0"
solana-client = "1.18.4"
solana-program = "1.18.4"
solana-sdk = "1.18.4"
